apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    volume: mysql-pv-volume
spec:
 capacity:
    storage: 1Gi
 accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
 gcePersistentDisk: 
  pdName: mysql
  fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: aigespring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
---