kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv-volume
spec:
 capacity:
    storage: 1Gi
 accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
 gcePersistentDisk: 
  pdName: mysql
  fsType: ext4