apiVersion: v1
kind: Service
metadata:
  name: springboot
  labels:
    app: aigespringboot
spec:
  ports:
    - protocol: TCP
      port: 8086
      targetPort: http
  selector:
    app: aigespringboot
    tier: backend
