apiVersion: apps/v1 
kind: Deployment
metadata:
  name: springboot
  labels:
    app: aigespringboot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aigespringboot
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: aigespringboot
        tier: backend
    spec:
      containers:
      - name: springboot-container
        image: eckhardo/nre-spring-boot-docker
        ports:
        - containerPort: 8086
        env:
        - name: MYSQL_DB_USER
          valueFrom:
            secretKeyRef:
              name: demo-credentials
              key: username
        - name: MYSQL_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: demo-credentials
              key: password
        - name: MYSQL_DB_HOST
          valueFrom:
            secretKeyRef:
              name: demo-credentials
              key: host
        - name: MYSQL_DB_PORT
          valueFrom:
            secretKeyRef:
              name: demo-credentials
              key: port